[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
quote = "1.0"
syn = "2.0"
rustfmt-wrapper = "0.2.1"
convert_case = "0.6"
proc-macro2 = "1.0.76"